"""add supplier_documents and update suppliers

Revision ID: 6570699963b2
Revises: 0ffc1a2c9edf
Create Date: 2026-03-15 02:37:50.988629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6570699963b2'
down_revision: Union[str, None] = '0ffc1a2c9edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_documents_id'), 'supplier_documents', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_documents_supplier_id'), 'supplier_documents', ['supplier_id'], unique=False)
    op.add_column('suppliers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.drop_column('suppliers', 'contact_email')
    op.drop_column('suppliers', 'contact_name')
    op.drop_column('suppliers', 'contact_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('contact_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('suppliers', 'phone')
    op.drop_index(op.f('ix_supplier_documents_supplier_id'), table_name='supplier_documents')
    op.drop_index(op.f('ix_supplier_documents_id'), table_name='supplier_documents')
    op.drop_table('supplier_documents')
    # ### end Alembic commands ###
