"""add_retetions supplier and requisition

Revision ID: 870e4db3396e
Revises: 20260502_000000
Create Date: 2026-05-02 17:20:29.227240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870e4db3396e'
down_revision: Union[str, None] = '20260502_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_retentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('retention_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['retention_id'], ['retentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'retention_id', name='uq_supplier_retention')
    )
    op.create_index(op.f('ix_supplier_retentions_id'), 'supplier_retentions', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_retentions_retention_id'), 'supplier_retentions', ['retention_id'], unique=False)
    op.create_index(op.f('ix_supplier_retentions_supplier_id'), 'supplier_retentions', ['supplier_id'], unique=False)
    op.create_table('requisition_retentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('retention_id', sa.Integer(), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retention_id'], ['retentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'retention_id', name='uq_requisition_retention')
    )
    op.create_index(op.f('ix_requisition_retentions_id'), 'requisition_retentions', ['id'], unique=False)
    op.create_index(op.f('ix_requisition_retentions_requisition_id'), 'requisition_retentions', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_requisition_retentions_retention_id'), 'requisition_retentions', ['retention_id'], unique=False)
    op.drop_constraint('password_resets_token_hash_key', 'password_resets', type_='unique')
    op.drop_constraint('requisitions_retention_id_fkey', 'requisitions', type_='foreignkey')
    op.drop_column('requisitions', 'retention_amount')
    op.drop_column('requisitions', 'retention_id')
    op.add_column('retentions', sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('retentions', 'due_date')
    op.add_column('requisitions', sa.Column('retention_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requisitions', sa.Column('retention_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key('requisitions_retention_id_fkey', 'requisitions', 'retentions', ['retention_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('password_resets_token_hash_key', 'password_resets', ['token_hash'])
    op.drop_index(op.f('ix_requisition_retentions_retention_id'), table_name='requisition_retentions')
    op.drop_index(op.f('ix_requisition_retentions_requisition_id'), table_name='requisition_retentions')
    op.drop_index(op.f('ix_requisition_retentions_id'), table_name='requisition_retentions')
    op.drop_table('requisition_retentions')
    op.drop_index(op.f('ix_supplier_retentions_supplier_id'), table_name='supplier_retentions')
    op.drop_index(op.f('ix_supplier_retentions_retention_id'), table_name='supplier_retentions')
    op.drop_index(op.f('ix_supplier_retentions_id'), table_name='supplier_retentions')
    op.drop_table('supplier_retentions')
    # ### end Alembic commands ###
