"""add_folio_serie_requisition

Revision ID: 8b40cc099e7f
Revises: c321f71aa2f2
Create Date: 2026-05-01 20:14:19.590275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b40cc099e7f'
down_revision: Union[str, None] = 'c321f71aa2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configuration', sa.Column('requisition_serie', sa.String(length=20), nullable=True))
    op.add_column('system_configuration', sa.Column('requisition_folio_next', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'requisition_folio_next')
    op.drop_column('system_configuration', 'requisition_serie')
    # ### end Alembic commands ###
