"""null request by at requisitions

Revision ID: 92d60bea158c
Revises: 20260403_130000
Create Date: 2026-04-05 03:15:20.775348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d60bea158c'
down_revision: Union[str, None] = '20260403_130000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisitions', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requisitions', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
