"""add_logo_configuration

Revision ID: c192f493084a
Revises: 8b40cc099e7f
Create Date: 2026-05-01 20:50:45.910813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c192f493084a'
down_revision: Union[str, None] = '8b40cc099e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_configuration', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configuration', 'logo_url')
    # ### end Alembic commands ###
