"""add_purchease order requisition

Revision ID: e5775aad339f
Revises: 870e4db3396e
Create Date: 2026-05-03 03:28:16.291386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5775aad339f'
down_revision: Union[str, None] = '870e4db3396e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('purchase_order', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisitions', 'purchase_order')
    # ### end Alembic commands ###
