"""add role permissions

Revision ID: ec36c5f038f1
Revises: 20260307_195349
Create Date: 2026-03-08 03:42:17.543559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec36c5f038f1'
down_revision: Union[str, None] = '20260307_195349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('catalog_action_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_action_id'], ['catalog_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'catalog_action_id', name='uq_role_catalog_action')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index('ix_audit_log_action_module', 'audit_log', ['action', 'module'], unique=False)
    op.create_index('ix_audit_log_module_date', 'audit_log', ['module', 'date'], unique=False)
    op.create_index('ix_audit_log_user_date', 'audit_log', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_user_date', table_name='audit_log')
    op.drop_index('ix_audit_log_module_date', table_name='audit_log')
    op.drop_index('ix_audit_log_action_module', table_name='audit_log')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
